[package]
name = "vendetta_import"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
vendetta_core = { workspace = true }
vendetta_model = { workspace = true }
vendetta_storage = { workspace = true }
vendetta_media = { workspace = true }
vendetta_render = { workspace = true }
grammers-tl-types = { workspace = true }
rusqlite = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
scraper = { workspace = true }
zip = { workspace = true }
anyhow = { workspace = true }

